In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [ ]:
am=pd.read_csv('/content/animal health condition.csv')

In [ ]:
am

,AnimalName,symptoms1,symptoms2,symptoms3,symptoms4,symptoms5,Dangerous
0,Dog,Fever,Diarrhea,Vomiting,Weight loss,Dehydration,Yes
1,Dog,Fever,Diarrhea,Coughing,Tiredness,Pains,Yes
2,Dog,Fever,Diarrhea,Coughing,Vomiting,Anorexia,Yes
3,Dog,Fever,Difficulty breathing,Coughing,Lethargy,Sneezing,Yes
4,Dog,Fever,Diarrhea,Coughing,Lethargy,Blue Eye,Yes
...,...,...,...,...,...,...,...
866,Buffaloes,Fever,Difficulty breathing,Poor Appetite,Eye and Skin change,Unable to exercise,Yes
867,Buffaloes,Fever,Loss of appetite,Lession on the skin,Lethargy,Joint Pain,Yes
868,Buffaloes,Lesions in the nasal cavity,Lesions on nose,Vomiting,Noisy Breathing,Lesions on nose,Yes
869,Buffaloes,Hair loss,Dandruff,Vomiting,Crusting of the skin,Ulcerated skin,Yes
870,Buffaloes,Greenish-yellow nasal discharge,Lack of pigmentation,Vomiting,Lethargy,Pain on face,Yes

In [ ]:
am.shape

(871, 7)

In [ ]:
am.describe()

,AnimalName,symptoms1,symptoms2,symptoms3,symptoms4,symptoms5,Dangerous
count,871,871,871,871,871,871,869
unique,46,232,230,229,217,203,2
top,Buffaloes,Fever,Diarrhea,Coughing,Weight loss,Pains,Yes
freq,129,257,119,95,117,99,849

In [ ]:
am.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 871 entries, 0 to 870
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   AnimalName  871 non-null    object
 1   symptoms1   871 non-null    object
 2   symptoms2   871 non-null    object
 3   symptoms3   871 non-null    object
 4   symptoms4   871 non-null    object
 5   symptoms5   871 non-null    object
 6   Dangerous   869 non-null    object
dtypes: object(7)
memory usage: 47.8+ KB

In [ ]:
le=LabelEncoder()

In [ ]:
am['AnimalName']=le.fit_transform(am['AnimalName'])

In [ ]:
am['symptoms1']=le.fit_transform(am['symptoms1'])

In [ ]:
am['symptoms2']=le.fit_transform(am['symptoms2'])

In [ ]:
am['symptoms3']=le.fit_transform(am['symptoms3'])

In [ ]:
am['symptoms4']=le.fit_transform(am['symptoms4'])

In [ ]:
am['symptoms5']=le.fit_transform(am['symptoms5'])

In [ ]:
am['Dangerous']=le.fit_transform(am['Dangerous'])

In [ ]:
am

,AnimalName,symptoms1,symptoms2,symptoms3,symptoms4,symptoms5,Dangerous
0,6,63,31,179,182,32,1
1,6,63,31,31,165,113,1
2,6,63,31,31,173,8,1
3,6,63,34,31,87,142,1
4,6,63,31,31,87,21,1
...,...,...,...,...,...,...,...
866,2,63,34,115,53,160,1
867,2,63,95,88,87,78,1
868,2,97,90,179,107,82,1
869,2,77,26,179,27,159,1
870,2,75,84,179,87,111,1

In [ ]:
X=am.drop(columns=['Dangerous'],axis=1)
Y=am['Dangerous']

In [ ]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,stratify=Y,random_state=42)

In [ ]:
model=LogisticRegression()

In [ ]:
model.fit(X_train,Y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [ ]:
X_train_prediction=model.predict(X_train)
traning_data_accuracy=accuracy_score(X_train_prediction,Y_train)

In [ ]:
print('Accuracy on traning data:',traning_data_accuracy)

Accuracy on traning data: 0.9770114942528736

In [ ]:
X_test_prediction=model.predict(X_test)
test_data_accuracy=accuracy_score(X_test_prediction,Y_test)

In [ ]:
print('accuracy on test data:',test_data_accuracy)

accuracy on test data: 0.9714285714285714

In [ ]:
input=(6,	63,	34,	31,	87,	142)

In [ ]:
numpy_array=np.asarray(input)

In [ ]:
reshape=numpy_array.reshape(1,-1)

In [ ]:
prediction=model.predict(reshape)
print(prediction)

if prediction ==0:
  print("The condition of animal is stable")
elif prediction==1:
  print("The condition of animal is not stable")
else:
  print(none)

[1]
The condition of animal is not stable

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(